### ISSUE TITLE
String index bug

### ISSUE THREAD

**Issue by projectstann** [numbworks/NW.NGramTextClassification#1]
When I invoke the .PredictLabel method with some inputs, a call to Substring() throws an unhandled exception up the stack.

at System.String.Substring(Int32 startIndex, Int32 length)
   at NW.NGramTextClassification.TextClassifierComponents.<>c.<.cctor>b__31_1(String text, UInt32 length)
   at NW.NGramTextClassification.TextClassifier.PredictLabel(String text, ITokenizationStrategy strategy, INGramTokenizerRuleSet ruleSet, List`1 labeledExamples)
   at NW.NGramTextClassification.TextClassifier.PredictLabel(String text, List`1 labeledExamples)
   at ****.InferReporterType(String input) in ****:line 100

**Comment by projectstann** [comment]
I've dug a little more and this appears to be a bug in the truncation code in LabeledExample.cs:43.  I'm not sure how my input is causing this, but this is the only call to Substring I can find in all the production code.

**Comment by numbworks** [comment]
@projectstann 
Thank you for reporting the bug! 

Do you have an example of the data you are feeding to the library so that I can recreate the bug?

**Comment by projectstann** [comment]
No problem. To simplify things, I just used the examples from your GitHub page and I get the same error. 

 public static List<LabeledExample> GenerateExamples()
        {
            List<(string label, string text)> tuples = new List<(string label, string text)>()
            { 
                ("en", "VerksamhetsbeskrivningGoGift is a company which focuses on [...]"),
                ("en", "You will report to the Team Manager. You will get the opportunity [...]")  
            };

            return new LabeledExampleFactory().Create(tuples);
        }

        ITextClassifier textClassifier = new TextClassifier();// new TextClassifier(new TextClassifierComponents(), new TextClassifierSettings(0));
        public string InferReporterType(string input)
        {
            TextClassifierResult result;
            try
            {
                Console.WriteLine("Input: " + input);
                result = textClassifier.PredictLabel(input, labeledExamples);
                Console.WriteLine("Output: " + result.Label);
                return result.Label;
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e.Message);
            }
            return "Unknown";
        }

**Comment by projectstann** [comment]
The Substring exception is thrown on the call to .PredictLabel.

**Comment by numbworks** [comment]
I'll try to allocate some time to look into it in the next evenings and get back to you! Thanks!

**Comment by projectstann** [comment]
Let me know if I can help you pinpoint the issue. It may be something non-obvious because it looks like you have a lot of unit tests that cover your own basic test cases.

**Comment by numbworks** [comment]
@projectstann 
I spent a bunch of hours debugging the issue you found in `NW.NGramTextClassification v1.0.0`, and I did solve it.

The problem was in `DefaultTextTruncatingFunction`, which has been rewritten from scratch in order to solve it.
Fixing the bug exposed a pair of additional bugs, which have been fixed as well. 

With a test coverage of `ca. 92%` these bugs were really hard to spot.

All the fixes will be included in the new version of the library that I'm going to push in the next few hours.
Please download it and try it out 😊

The following `Program.cs`:

```csharp

using System;
using System.Collections.Generic;
using NW.NGramTextClassification;

namespace NW.NGramTextClassificationClient
{
    class Program
    {
        static void Main(string[] args)
        {

            string label = InferReporterType("some");
            Console.WriteLine(label);

            Console.ReadKey();

        }
        static List<LabeledExample> GenerateExamples()
        {
            List<(string label, string text)> tuples = new List<(string label, string text)>()
            {
                ("en", "VerksamhetsbeskrivningGoGift is a company which focuses on [...]"),
                ("en", "You will report to the Team Manager. You will get the opportunity [...]")
            };

            return new LabeledExampleFactory().Create(tuples);

        }
        static string InferReporterType(string input)
        {

            List<LabeledExample> labeledExamples = GenerateExamples();
            ITextClassifier textClassifier = new TextClassifier();

            TextClassifierResult result;
            try
            {
                Console.WriteLine("Input: " + input);
                result = textClassifier.PredictLabel(input, labeledExamples);
                Console.WriteLine("Output: " + result.Label);
                return result.Label;
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e.Message);
            }
            return "Unknown";
        }

    }
}

```

will return the following log:

```
Input: some
Attempting to predict the label of the provided text...
The following text has been provided: 'some'.
The following 'ITokenizationStrategy' object will be used: '[ Pattern: '[\w0-9_]{1,}', Delimiter: ' ', ToLowercase: 'True' ]'.
The following 'INGramTokenizerRuleSet' object will be used: '[ DoForMonograms: 'True', DoForBigrams: 'True', DoForTrigrams: 'True', DoForFourgrams: 'False', DoForFivegrams: 'False' ]'.
'2' LabeledExample objects have been provided.
The 'DoForBigrams' rule can't be applied to the provided string: 'some'.
Unknown
```
If you change the input string to `some string`:

```
Input: some string
Attempting to predict the label of the provided text...
The following text has been provided: 'some string'.
The following 'ITokenizationStrategy' object will be used: '[ Pattern: '[\w0-9_]{1,}', Delimiter: ' ', ToLowercase: 'True' ]'.
The following 'INGramTokenizerRuleSet' object will be used: '[ DoForMonograms: 'True', DoForBigrams: 'True', DoForTrigrams: 'True', DoForFourgrams: 'False', DoForFivegrams: 'False' ]'.
'2' LabeledExample objects have been provided.
The 'DoForTrigrams' rule can't be applied to the provided string: 'some string'.
Unknown
```

If you change the input string to `some string string`:

```
Input: some string string
Attempting to predict the label of the provided text...
The following text has been provided: 'some string string'.
The following 'ITokenizationStrategy' object will be used: '[ Pattern: '[\w0-9_]{1,}', Delimiter: ' ', ToLowercase: 'True' ]'.
The following 'INGramTokenizerRuleSet' object will be used: '[ DoForMonograms: 'True', DoForBigrams: 'True', DoForTrigrams: 'True', DoForFourgrams: 'False', DoForFivegrams: 'False' ]'.
'2' LabeledExample objects have been provided.
The provided text has been tokenized into '9' INGram object.
Comparing the provided text against the following LabeledExample: '[ Id: '1', Label: 'en', Text: 'Verksamhetsbeskrivni...', TextAsNGrams: '21' ]'...
The calculated 'SimilarityIndex' value is '0'.
The rounded 'SimilarityIndex' value is '0'.
The following SimilarityIndex object has been added to the list: '[ Id: '1', Label: 'en', Value: '0' ]'.
Comparing the provided text against the following LabeledExample: '[ Id: '2', Label: 'en', Text: 'You will report to t...', TextAsNGrams: '36' ]'...
The calculated 'SimilarityIndex' value is '0'.
The rounded 'SimilarityIndex' value is '0'.
The following SimilarityIndex object has been added to the list: '[ Id: '2', Label: 'en', Value: '0' ]'.
The tokenized text has been successfully compared against the provided list of LabeledExample objects.
'2' SimilarityIndex objects have been computed.
The following unique labels have been found in the provided SimilarityIndex list: '[en]'.
Calculating 'SimilarityIndexAverage' for the following label: 'en'...
The calculated 'SimilarityIndexAverage' value is '0'.
The rounded 'SimilarityIndexAverage' value is '0'.
The following SimilarityIndexAverage object has been added to the list: '[ Label: 'en', Value: '0' ]'.
'1' SimilarityIndexAverage objects have been computed.
The following verification has failed: 'ContainsAtLeastOneIndexAverageThatIsNotZero'.
The predicted label is: ''.
The prediction has failed. Try increasing the amount of provided LabeledExample objects.
Output:
```

**Comment by numbworks** [comment]
UPDATE: [NW.NGramTextClassification v1.1.0](https://www.nuget.org/packages/NW.NGramTextClassification/1.1.0) is up 😊

**Comment by projectstann** [comment]
Excellent! Thanks for putting in the time to fix it. I'll download the new version soon. 😁.

I'll let you know how it goes.
