### ISSUE TITLE
add data to model when app is running and use 

### ISSUE THREAD

**Issue by sapurtcomputer30** [numbworks/NW.NGramTextClassification#21]
I am trying to make a talking bot using this library

I admit that the library is incredibly beautiful and the work is set up

But I wanted to know how I can add data to the model when app is running using this library and save it at runtime.

**Comment by numbworks** [comment]
Hey Mohammad,

thank you for playing out with my package!

Would you mind to describe a bit more about your specific use case scenario?

And do you use is as library in your own C# project or do you use it as executable in a script?

**Comment by sapurtcomputer30** [comment]
> Hey Mohammad,
> 
> thank you for playing out with my package!
> 
> Would you mind to describe a bit more about your specific use case scenario?
> 
> And do you use is as library in your own C# project or do you use it as executable in a script?

I am trying to complete my project with this package because it is very accurate and it is the answer for me. The scenario I am implementing is analyzing and categorizing my forum questions thematically I need two vital things in this package 1- Teaching labeled data and saving it and the possibility of reusing it 2- A way to implement active learning with this library and train more data to increase model accuracy over time The latter is very important to me because I currently have very little labeled data and most of my data is unlabeled. are tags (almost 6 million messages)

**Comment by numbworks** [comment]
Thank you for your suggestion.

You can already do that that by writing your own method around the classifier.

I don't know if you are calling the DLL from C# or Powershell or another language, but here an example in C# that you can replicate easily in other languages as well:

```csharp
using NW.NGramTextClassification;

namespace YourOwnApplication
{
    class Program
    {

        static int Main(string[] args)
        {

            List<TextSnippet> textSnippets = GetTextSnippets();
            IFileInfoAdapter jsonFile = GetLabeledExampleJsonFile();

            ITextClassifier textClassifier = new TextClassifier();
            foreach (TextSnippet textSnippet in textSnippets)
            {

                TextClassifierSession textClassifierSession
                        = LoadSaveAndClassify(textClassifier, textSnippet, jsonFile);

                // Handle Session

            }

            // Handle exit code
            return 0;

        }

        private static List<TextSnippet> GetTextSnippets() { /* .... */ }
        private static IFileInfoAdapter GetLabeledExampleJsonFile() { /* .... */ }

        private static TextClassifierSession LoadSaveAndClassify
            (ITextClassifier textClassifier, TextSnippet textSnippet, IFileInfoAdapter jsonFile)
        {

            List<LabeledExample> labeledExamples
                = textClassifier.LoadLabeledExamplesOrDefault(jsonFile);

            TextClassifierSession textClassifierSession
                = textClassifier.ClassifyOrDefault(textSnippet, labeledExamples);

            LabeledExample labeledExample
                = new LabeledExample(
                        Label: textClassifierSession.Results[0].Label
                        Text: textClassifierSession.Results[0].TextSnippet.Text
                        );

            labeledExamples.Add(labeledExample);

            textClassifier.SaveLabeledExamples(labeledExamples, jsonFile.FullName);

            return textClassifierSession;

        }

    }

}
```

Obviously, you need to add some error handling logic as well, according to your need.
