### ISSUE TITLE
Add Load CSV Method to load labeld Examples from csv file

### ISSUE THREAD

**Issue by sapurtcomputer30** [numbworks/NW.NGramTextClassification#22]
Please add the ReadCSV method with CSV Helper  library

https://joshclose.github.io/CsvHelper/

**Comment by numbworks** [comment]
Hey,

thank you for reaching out!

There will be a first implementation of this feature in the next version. I already written the code, I just need to clean it and push it. Probably it will be available by the end of the year. 

A more expanded version will hopefully come in 2023, but only after some work planned for other libraries will be completed.

NW

**Comment by numbworks** [comment]
@sapurtcomputer30 
If you look into the repository from now on, you'll find a Powershell script in the "scripts" sub-folder that does what you need (CSV files to LabeledExamples/TextSnippet JSON files).

A more integrated version of this feature may or may not come in the future. 

Cheers!
